export const LOAD_EPISODE_STARTED = 'LOAD_EPISODE_STARTED';
export const LOAD_EPISODE_SUCCEEDED = 'LOAD_EPISODE_SUCCEEDED';
export const LOAD_EPISODE_FAILED = 'LOAD_EPISODE_FAILED';
export const CLEAR_EPISODE = 'CLEAR_EPISODE';
